import { useState } from "react";
import { useNavigate } from "react-router-dom";
import styles from "./PettyCash.module.css";

function PettyCash() {
  const navigate = useNavigate();

  const [cash, setCash] = useState({
    ref_no: "",
    date: "",
    entry_type: "Debit",
    account: "",
    detail: "",
    amount: "",
    user: "admin",
    remarks: ""
  });

  const [data, setData] = useState([]);
  const [open, setOpen] = useState(false);
  const [editMode, setEditMode] = useState(false);
  const [editId, setEditId] = useState(null);
  const [search, setSearch] = useState("");
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 5;

  const handleChange = (e) => {
    setCash({
      ...cash,
      [e.target.name]: e.target.value
    });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    
    // Validation
    if (!cash.ref_no) {
      alert("Please enter reference number");
      return;
    }
    if (!cash.date) {
      alert("Please select date");
      return;
    }
    if (!cash.account) {
      alert("Please enter account name");
      return;
    }
    if (!cash.amount || cash.amount <= 0) {
      alert("Please enter valid amount");
      return;
    }

    if (editMode) {
      // Update existing entry
      const updatedData = data.map(item => 
        item.id === editId ? { ...cash, id: editId } : item
      );
      setData(updatedData);
      alert("Petty cash entry updated successfully!");
    } else {
      // Add new entry
      const newData = {
        ...cash,
        id: Date.now()
      };
      setData([...data, newData]);
      alert("Petty cash entry saved successfully!");
    }

    // Reset form
    setCash({
      ref_no: "",
      date: "",
      entry_type: "Debit",
      account: "",
      detail: "",
      amount: "",
      user: "admin",
      remarks: ""
    });
    setOpen(false);
    setEditMode(false);
    setEditId(null);
  };

  const handleEdit = (item) => {
    setCash({
      ref_no: item.ref_no,
      date: item.date,
      entry_type: item.entry_type,
      account: item.account,
      detail: item.detail,
      amount: item.amount,
      user: item.user,
      remarks: item.remarks || ""
    });
    setEditMode(true);
    setEditId(item.id);
    setOpen(true);
  };

  const handleDelete = (id) => {
    if (window.confirm("Are you sure you want to delete this entry?")) {
      setData(data.filter(item => item.id !== id));
      alert("Entry deleted successfully!");
    }
  };

  const handlePrint = (item) => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>Petty Cash Voucher</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; }
            .header { text-align: center; margin-bottom: 30px; }
            .voucher { border: 1px solid #ddd; padding: 20px; border-radius: 10px; }
            .row { display: flex; margin-bottom: 10px; }
            .label { font-weight: bold; width: 120px; }
            .value { flex: 1; }
            .amount { font-size: 24px; font-weight: bold; color: #ffa600; margin-top: 20px; }
            hr { margin: 20px 0; }
          </style>
        </head>
        <body>
          <div class="header">
            <h2>Petty Cash Voucher</h2>
          </div>
          <div class="voucher">
            <div class="row"><div class="label">Reference No:</div><div class="value">${item.ref_no}</div></div>
            <div class="row"><div class="label">Date:</div><div class="value">${item.date}</div></div>
            <div class="row"><div class="label">Entry Type:</div><div class="value">${item.entry_type}</div></div>
            <div class="row"><div class="label">Account:</div><div class="value">${item.account}</div></div>
            <div class="row"><div class="label">Detail:</div><div class="value">${item.detail}</div></div>
            <div class="row"><div class="label">User:</div><div class="value">${item.user}</div></div>
            <div class="row"><div class="label">Remarks:</div><div class="value">${item.remarks || '-'}</div></div>
            <hr />
            <div class="amount">Amount: ₨ ${parseFloat(item.amount).toLocaleString()}</div>
          </div>
          <div style="text-align: center; margin-top: 30px;">
            <p>Generated by Tailor Soft System</p>
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  // Search filter
  const filteredData = data.filter((item) =>
    item.ref_no?.toLowerCase().includes(search.toLowerCase()) ||
    item.account?.toLowerCase().includes(search.toLowerCase()) ||
    item.entry_type?.toLowerCase().includes(search.toLowerCase())
  );

  // Pagination
  const indexOfLastItem = currentPage * itemsPerPage;
  const indexOfFirstItem = indexOfLastItem - itemsPerPage;
  const currentItems = filteredData.slice(indexOfFirstItem, indexOfLastItem);
  const totalPages = Math.ceil(filteredData.length / itemsPerPage);

  const formatCurrency = (value) => {
    return new Intl.NumberFormat('en-PK', {
      style: 'currency',
      currency: 'PKR',
      minimumFractionDigits: 0
    }).format(value || 0);
  };

  const calculateTotalAmount = () => {
    const total = data.reduce((sum, item) => sum + (parseFloat(item.amount) || 0), 0);
    return formatCurrency(total);
  };

  return (
    <div className={styles.container}>
      <div className={styles.card}>
        <div className={styles.header}>
          <h1 className={styles.title}>Petty Cash Voucher</h1>
          <p className={styles.subtitle}>Manage petty cash transactions</p>
        </div>

        <div className={styles.topBar}>
          <div className={styles.searchWrapper}>
            <input
              type="text"
              placeholder="🔍 Search by reference, account or type..."
              className={styles.search}
              value={search}
              onChange={(e) => {
                setSearch(e.target.value);
                setCurrentPage(1);
              }}
            />
          </div>
          <button className={styles.addBtn} onClick={() => setOpen(true)}>
            + New Voucher
          </button>
        </div>

        {/* Summary Card */}
        {data.length > 0 && (
          <div className={styles.summaryCard}>
            <div className={styles.summaryIcon}>💰</div>
            <div className={styles.summaryContent}>
              <span className={styles.summaryLabel}>Total Petty Cash Amount</span>
              <span className={styles.summaryAmount}>{calculateTotalAmount()}</span>
            </div>
            <div className={styles.summaryCount}>
              <span>{data.length} Transactions</span>
            </div>
          </div>
        )}

        <div className={styles.tableWrapper}>
          <table className={styles.table}>
            <thead>
              <tr>
                <th>Ref No</th>
                <th>Date</th>
                <th>Type</th>
                <th>Account</th>
                <th>Detail</th>
                <th>Amount</th>
                <th>User</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {currentItems.length === 0 ? (
                <tr>
                  <td colSpan="8" className={styles.emptyCell}>
                    <div className={styles.emptyState}>
                      <span>💰</span>
                      <p>No petty cash entries found</p>
                      <small>Click "New Voucher" to add one</small>
                    </div>
                  </td>
                </tr>
              ) : (
                currentItems.map((item) => (
                  <tr key={item.id}>
                    <td><strong>{item.ref_no}</strong></td>
                    <td>{item.date}</td>
                    <td className={item.entry_type === "Debit" ? styles.debit : styles.credit}>
                      {item.entry_type === "Debit" ? "📥 Debit" : "📤 Credit"}
                    </td>
                    <td>{item.account}</td>
                    <td>{item.detail || "-"}</td>
                    <td className={styles.amountCell}>{formatCurrency(item.amount)}</td>
                    <td>{item.user}</td>
                    <td className={styles.actions}>
                      <button className={styles.editBtn} onClick={() => handleEdit(item)} title="Edit">
                        ✏️
                      </button>
                      <button className={styles.deleteBtn} onClick={() => handleDelete(item.id)} title="Delete">
                        🗑️
                      </button>
                      <button className={styles.printBtn} onClick={() => handlePrint(item)} title="Print">
                        🖨️
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {totalPages > 1 && (
          <div className={styles.pagination}>
            <button
              onClick={() => setCurrentPage(prev => Math.max(prev - 1, 1))}
              disabled={currentPage === 1}
              className={styles.pageBtn}
            >
              ← Previous
            </button>
            <div className={styles.pageNumbers}>
              {Array.from({ length: totalPages }, (_, index) => (
                <button
                  key={index}
                  onClick={() => setCurrentPage(index + 1)}
                  className={currentPage === index + 1 ? styles.activePage : ""}
                >
                  {index + 1}
                </button>
              ))}
            </div>
            <button
              onClick={() => setCurrentPage(prev => Math.min(prev + 1, totalPages))}
              disabled={currentPage === totalPages}
              className={styles.pageBtn}
            >
              Next →
            </button>
          </div>
        )}
      </div>

      {/* MODAL */}
      {open && (
        <div className={styles.modal}>
          <div className={styles.modalContent}>
            <div className={styles.modalHeader}>
              <h3>{editMode ? "Edit Petty Cash Voucher" : "New Petty Cash Voucher"}</h3>
              <button className={styles.closeBtn} onClick={() => {
                setOpen(false);
                setEditMode(false);
                setCash({
                  ref_no: "",
                  date: "",
                  entry_type: "Debit",
                  account: "",
                  detail: "",
                  amount: "",
                  user: "admin",
                  remarks: ""
                });
              }}>✕</button>
            </div>

            <form onSubmit={handleSubmit}>
              <div className={styles.grid}>
                <div className={styles.field}>
                  <label>Reference No *</label>
                  <input type="text" name="ref_no" value={cash.ref_no} onChange={handleChange} placeholder="PC-001" required />
                </div>

                <div className={styles.field}>
                  <label>Date *</label>
                  <input type="date" name="date" value={cash.date} onChange={handleChange} required />
                </div>

                <div className={styles.field}>
                  <label>Entry Type</label>
                  <select name="entry_type" value={cash.entry_type} onChange={handleChange}>
                    <option value="Debit">📥 Debit</option>
                    <option value="Credit">📤 Credit</option>
                  </select>
                </div>

                <div className={styles.field}>
                  <label>Account *</label>
                  <input type="text" name="account" value={cash.account} onChange={handleChange} placeholder="Enter account name" required />
                </div>

                <div className={styles.field}>
                  <label>Detail</label>
                  <input type="text" name="detail" value={cash.detail} onChange={handleChange} placeholder="Enter detail" />
                </div>

                <div className={styles.field}>
                  <label>Amount (₨) *</label>
                  <input type="number" name="amount" value={cash.amount} onChange={handleChange} placeholder="Enter amount" required step="any" />
                </div>

                <div className={styles.field}>
                  <label>User</label>
                  <input type="text" name="user" value={cash.user} onChange={handleChange} />
                </div>

                <div className={styles.fullWidth}>
                  <label>Remarks</label>
                  <textarea name="remarks" value={cash.remarks} onChange={handleChange} placeholder="Enter remarks..." rows="3" />
                </div>
              </div>

              <div className={styles.modalActions}>
                <button type="button" className={styles.cancelBtn} onClick={() => {
                  setOpen(false);
                  setEditMode(false);
                }}>Cancel</button>
                <button type="submit" className={styles.saveBtn}>
                  {editMode ? "💾 Update Voucher" : "💾 Save Voucher"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}

export default PettyCash;