import React, { useState } from "react";
import styles from "./ExtraStitches.module.css";

function ExtraStitches() {
  const [stitches, setStitches] = useState([
    { id: 1, name: "FDS" },
    { id: 2, name: "Double Stitch" },
    { id: 3, name: "Chain Stitch" },
    { id: 4, name: "Zigzag Stitch" },
    { id: 5, name: "Overlock Stitch" }
  ]);
  const [showForm, setShowForm] = useState(false);
  const [editId, setEditId] = useState(null);
  const [stitchName, setStitchName] = useState("");
  const [search, setSearch] = useState("");
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(10);

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!stitchName) return alert("Please enter stitch name");
    
    if (editId) {
      setStitches(stitches.map(s => s.id === editId ? { ...s, name: stitchName } : s));
      alert("Stitch updated successfully!");
    } else {
      setStitches([...stitches, { id: Date.now(), name: stitchName }]);
      alert("Stitch added successfully!");
    }
    
    setStitchName("");
    setEditId(null);
    setShowForm(false);
  };

  const handleEdit = (item) => {
    setStitchName(item.name);
    setEditId(item.id);
    setShowForm(true);
  };

  const handleDelete = (id) => {
    if (window.confirm("Are you sure you want to delete this stitch?")) {
      setStitches(stitches.filter(s => s.id !== id));
      alert("Stitch deleted successfully!");
    }
  };

  const handlePrint = (item) => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head><title>Stitch Details - ${item.name}</title></head>
        <body style="font-family:Arial;padding:40px;text-align:center">
          <h2>Extra Stitch Details</h2>
          <hr/>
          <p><strong>ID:</strong> ${item.id}</p>
          <p><strong>Name:</strong> ${item.name}</p>
          <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
          <hr/>
          <p>Generated by Tailor Soft System</p>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  const filteredStitches = stitches.filter(s => 
    s.name.toLowerCase().includes(search.toLowerCase())
  );
  
  const indexOfLastItem = currentPage * itemsPerPage;
  const indexOfFirstItem = indexOfLastItem - itemsPerPage;
  const currentItems = filteredStitches.slice(indexOfFirstItem, indexOfLastItem);
  const totalPages = Math.ceil(filteredStitches.length / itemsPerPage);

  return (
    <div className={styles.container}>
      <div className={styles.card}>
        
        {/* Header */}
        <div className={styles.header}>
          <h1 className={styles.title}>Extra Stitches</h1>
          <div className={styles.totalCount}>{stitches.length} Total</div>
        </div>

        {/* Search & Add */}
        <div className={styles.toolbar}>
          <input 
            type="text" 
            placeholder="Search stitches..." 
            value={search}
            onChange={(e) => { setSearch(e.target.value); setCurrentPage(1); }}
            className={styles.search}
          />
          <button onClick={() => { setShowForm(true); setEditId(null); setStitchName(""); }} className={styles.addBtn}>
            + Add Stitch
          </button>
        </div>

        {/* Items Per Page */}
        <div className={styles.perPage}>
          <span>Show:</span>
          <select value={itemsPerPage} onChange={(e) => { setItemsPerPage(Number(e.target.value)); setCurrentPage(1); }}>
            <option value={5}>5</option>
            <option value={10}>10</option>
            <option value={25}>25</option>
            <option value={50}>50</option>
          </select>
        </div>

        {/* Table */}
        <table className={styles.table}>
          <thead>
            <tr>
              <th>#</th>
              <th>Stitch Name</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {currentItems.length === 0 ? (
              <tr>
                <td colSpan="3" className={styles.empty}>No stitches found</td>
              </tr>
            ) : (
              currentItems.map((stitch, index) => (
                <tr key={stitch.id}>
                  <td>{indexOfFirstItem + index + 1}</td>
                  <td className={styles.nameCell}>{stitch.name}</td>
                  <td className={styles.actionsCell}>
                    <button onClick={() => handleEdit(stitch)} className={styles.editBtn} title="Edit">
                      ✏️
                    </button>
                    <button onClick={() => handleDelete(stitch.id)} className={styles.deleteBtn} title="Delete">
                      🗑️
                    </button>
                    <button onClick={() => handlePrint(stitch)} className={styles.printBtn} title="Print">
                      🖨️
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>

        {/* Pagination */}
        {totalPages > 1 && (
          <div className={styles.pagination}>
            <button onClick={() => setCurrentPage(p => p-1)} disabled={currentPage === 1}>← Previous</button>
            <span>Page {currentPage} of {totalPages}</span>
            <button onClick={() => setCurrentPage(p => p+1)} disabled={currentPage === totalPages}>Next →</button>
          </div>
        )}
      </div>

      {/* Modal Form */}
      {showForm && (
        <div className={styles.modal}>
          <div className={styles.modalBox}>
            <div className={styles.modalHeader}>
              <h3>{editId ? "Edit Stitch" : "Add New Stitch"}</h3>
              <button onClick={() => setShowForm(false)}>✕</button>
            </div>
            <form onSubmit={handleSubmit}>
              <input 
                type="text" 
                value={stitchName}
                onChange={(e) => setStitchName(e.target.value)}
                placeholder="Enter stitch name (e.g., FDS, Double Stitch)"
                required
                autoFocus
              />
              <div className={styles.modalButtons}>
                <button type="button" onClick={() => setShowForm(false)}>Cancel</button>
                <button type="submit">Save</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}

export default ExtraStitches;