import { useState } from "react";
import { useNavigate } from "react-router-dom";
import styles from "./BankPayment.module.css";

function BankPayment() {
  const navigate = useNavigate();

  const [payment, setPayment] = useState({
    ref_no: "",
    bank_from: "",
    cheque_no: "",
    cheque_date: "",
    paid_to: "",
    amount: "",
    remarks: "",
    user: "admin"
  });

  const [data, setData] = useState([]);
  const [open, setOpen] = useState(false);
  const [editMode, setEditMode] = useState(false);
  const [editId, setEditId] = useState(null);
  const [search, setSearch] = useState("");
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 5;

  const handleChange = (e) => {
    setPayment({
      ...payment,
      [e.target.name]: e.target.value
    });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    
    // Validation
    if (!payment.ref_no) {
      alert("Please enter reference number");
      return;
    }
    if (!payment.bank_from) {
      alert("Please enter bank name");
      return;
    }
    if (!payment.cheque_no) {
      alert("Please enter cheque number");
      return;
    }
    if (!payment.paid_to) {
      alert("Please enter receiver name");
      return;
    }
    if (!payment.amount || payment.amount <= 0) {
      alert("Please enter valid amount");
      return;
    }

    if (editMode) {
      // Update existing entry
      const updatedData = data.map(item => 
        item.id === editId ? { ...payment, id: editId } : item
      );
      setData(updatedData);
      alert("Bank payment updated successfully!");
    } else {
      // Add new entry
      const newData = {
        ...payment,
        id: Date.now()
      };
      setData([...data, newData]);
      alert("Bank payment saved successfully!");
    }

    // Reset form
    setPayment({
      ref_no: "",
      bank_from: "",
      cheque_no: "",
      cheque_date: "",
      paid_to: "",
      amount: "",
      remarks: "",
      user: "admin"
    });
    setOpen(false);
    setEditMode(false);
    setEditId(null);
  };

  const handleEdit = (item) => {
    setPayment({
      ref_no: item.ref_no,
      bank_from: item.bank_from,
      cheque_no: item.cheque_no,
      cheque_date: item.cheque_date,
      paid_to: item.paid_to,
      amount: item.amount,
      remarks: item.remarks || "",
      user: item.user
    });
    setEditMode(true);
    setEditId(item.id);
    setOpen(true);
  };

  const handleDelete = (id) => {
    if (window.confirm("Are you sure you want to delete this payment?")) {
      setData(data.filter(item => item.id !== id));
      alert("Payment deleted successfully!");
    }
  };

  const handlePrint = (item) => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>Bank Payment Voucher</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; }
            .header { text-align: center; margin-bottom: 30px; }
            .voucher { border: 1px solid #ddd; padding: 20px; border-radius: 10px; }
            .row { display: flex; margin-bottom: 10px; }
            .label { font-weight: bold; width: 140px; }
            .value { flex: 1; }
            .amount { font-size: 24px; font-weight: bold; color: #ffa600; margin-top: 20px; }
            hr { margin: 20px 0; }
          </style>
        </head>
        <body>
          <div class="header">
            <h2>Bank Payment Voucher</h2>
          </div>
          <div class="voucher">
            <div class="row"><div class="label">Reference No:</div><div class="value">${item.ref_no}</div></div>
            <div class="row"><div class="label">Bank From:</div><div class="value">${item.bank_from}</div></div>
            <div class="row"><div class="label">Cheque No:</div><div class="value">${item.cheque_no}</div></div>
            <div class="row"><div class="label">Cheque Date:</div><div class="value">${item.cheque_date}</div></div>
            <div class="row"><div class="label">Paid To:</div><div class="value">${item.paid_to}</div></div>
            <div class="row"><div class="label">User:</div><div class="value">${item.user}</div></div>
            <div class="row"><div class="label">Remarks:</div><div class="value">${item.remarks || '-'}</div></div>
            <hr />
            <div class="amount">Amount: ₨ ${parseFloat(item.amount).toLocaleString()}</div>
          </div>
          <div style="text-align: center; margin-top: 30px;">
            <p>Generated by Tailor Soft System</p>
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  // Search filter
  const filteredData = data.filter((item) =>
    item.ref_no?.toLowerCase().includes(search.toLowerCase()) ||
    item.bank_from?.toLowerCase().includes(search.toLowerCase()) ||
    item.paid_to?.toLowerCase().includes(search.toLowerCase()) ||
    item.cheque_no?.toLowerCase().includes(search.toLowerCase())
  );

  // Pagination
  const indexOfLastItem = currentPage * itemsPerPage;
  const indexOfFirstItem = indexOfLastItem - itemsPerPage;
  const currentItems = filteredData.slice(indexOfFirstItem, indexOfLastItem);
  const totalPages = Math.ceil(filteredData.length / itemsPerPage);

  const formatCurrency = (value) => {
    return new Intl.NumberFormat('en-PK', {
      style: 'currency',
      currency: 'PKR',
      minimumFractionDigits: 0
    }).format(value || 0);
  };

  const calculateTotalAmount = () => {
    const total = data.reduce((sum, item) => sum + (parseFloat(item.amount) || 0), 0);
    return formatCurrency(total);
  };

  return (
    <div className={styles.container}>
      <div className={styles.card}>
        <div className={styles.header}>
          <h1 className={styles.title}>Bank Payment Voucher</h1>
          <p className={styles.subtitle}>Manage bank payment transactions</p>
        </div>

        <div className={styles.topBar}>
          <div className={styles.searchWrapper}>
            <input
              type="text"
              placeholder="🔍 Search by reference, bank, cheque or receiver..."
              className={styles.search}
              value={search}
              onChange={(e) => {
                setSearch(e.target.value);
                setCurrentPage(1);
              }}
            />
          </div>
          <button className={styles.addBtn} onClick={() => setOpen(true)}>
            + New Payment
          </button>
        </div>

        {/* Summary Card */}
        {data.length > 0 && (
          <div className={styles.summaryCard}>
            <div className={styles.summaryIcon}>💳</div>
            <div className={styles.summaryContent}>
              <span className={styles.summaryLabel}>Total Bank Payments</span>
              <span className={styles.summaryAmount}>{calculateTotalAmount()}</span>
            </div>
            <div className={styles.summaryCount}>
              <span>{data.length} Transactions</span>
            </div>
          </div>
        )}

        <div className={styles.tableWrapper}>
          <table className={styles.table}>
            <thead>
              <tr>
                <th>Ref No</th>
                <th>Bank From</th>
                <th>Cheque No</th>
                <th>Cheque Date</th>
                <th>Paid To</th>
                <th>Amount</th>
                <th>User</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {currentItems.length === 0 ? (
                <tr>
                  <td colSpan="8" className={styles.emptyCell}>
                    <div className={styles.emptyState}>
                      <span>💳</span>
                      <p>No bank payments found</p>
                      <small>Click "New Payment" to add one</small>
                    </div>
                  </td>
                </tr>
              ) : (
                currentItems.map((item) => (
                  <tr key={item.id}>
                    <td><strong>{item.ref_no}</strong></td>
                    <td>{item.bank_from}</td>
                    <td>{item.cheque_no}</td>
                    <td>{item.cheque_date}</td>
                    <td>{item.paid_to}</td>
                    <td className={styles.amountCell}>{formatCurrency(item.amount)}</td>
                    <td>{item.user}</td>
                    <td className={styles.actions}>
                      <button className={styles.editBtn} onClick={() => handleEdit(item)} title="Edit">
                        ✏️
                      </button>
                      <button className={styles.deleteBtn} onClick={() => handleDelete(item.id)} title="Delete">
                        🗑️
                      </button>
                      <button className={styles.printBtn} onClick={() => handlePrint(item)} title="Print">
                        🖨️
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {totalPages > 1 && (
          <div className={styles.pagination}>
            <button
              onClick={() => setCurrentPage(prev => Math.max(prev - 1, 1))}
              disabled={currentPage === 1}
              className={styles.pageBtn}
            >
              ← Previous
            </button>
            <div className={styles.pageNumbers}>
              {Array.from({ length: totalPages }, (_, index) => (
                <button
                  key={index}
                  onClick={() => setCurrentPage(index + 1)}
                  className={currentPage === index + 1 ? styles.activePage : ""}
                >
                  {index + 1}
                </button>
              ))}
            </div>
            <button
              onClick={() => setCurrentPage(prev => Math.min(prev + 1, totalPages))}
              disabled={currentPage === totalPages}
              className={styles.pageBtn}
            >
              Next →
            </button>
          </div>
        )}
      </div>

      {/* MODAL */}
      {open && (
        <div className={styles.modal}>
          <div className={styles.modalContent}>
            <div className={styles.modalHeader}>
              <h3>{editMode ? "Edit Bank Payment" : "New Bank Payment"}</h3>
              <button className={styles.closeBtn} onClick={() => {
                setOpen(false);
                setEditMode(false);
                setPayment({
                  ref_no: "",
                  bank_from: "",
                  cheque_no: "",
                  cheque_date: "",
                  paid_to: "",
                  amount: "",
                  remarks: "",
                  user: "admin"
                });
              }}>✕</button>
            </div>

            <form onSubmit={handleSubmit}>
              <div className={styles.grid}>
                <div className={styles.field}>
                  <label>Reference No *</label>
                  <input type="text" name="ref_no" value={payment.ref_no} onChange={handleChange} placeholder="BP-001" required />
                </div>

                <div className={styles.field}>
                  <label>Bank From *</label>
                  <input type="text" name="bank_from" value={payment.bank_from} onChange={handleChange} placeholder="Enter bank name" required />
                </div>

                <div className={styles.field}>
                  <label>Cheque No *</label>
                  <input type="text" name="cheque_no" value={payment.cheque_no} onChange={handleChange} placeholder="Enter cheque number" required />
                </div>

                <div className={styles.field}>
                  <label>Cheque Date</label>
                  <input type="date" name="cheque_date" value={payment.cheque_date} onChange={handleChange} />
                </div>

                <div className={styles.field}>
                  <label>Paid To *</label>
                  <input type="text" name="paid_to" value={payment.paid_to} onChange={handleChange} placeholder="Enter receiver name" required />
                </div>

                <div className={styles.field}>
                  <label>Amount (₨) *</label>
                  <input type="number" name="amount" value={payment.amount} onChange={handleChange} placeholder="Enter amount" required step="any" />
                </div>

                <div className={styles.field}>
                  <label>User</label>
                  <input type="text" name="user" value={payment.user} onChange={handleChange} />
                </div>

                <div className={styles.fullWidth}>
                  <label>Remarks</label>
                  <textarea name="remarks" value={payment.remarks} onChange={handleChange} placeholder="Enter remarks..." rows="3" />
                </div>
              </div>

              <div className={styles.modalActions}>
                <button type="button" className={styles.cancelBtn} onClick={() => {
                  setOpen(false);
                  setEditMode(false);
                }}>Cancel</button>
                <button type="submit" className={styles.saveBtn}>
                  {editMode ? "💾 Update Payment" : "💾 Save Payment"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}

export default BankPayment;